let level1 = {
  label: "Level 1",
  optimalMoves: 3, 
  playerStartingPosition: [[2, 1], [3, 1]], // [ [x, y], [x, y] ]
  map: [
    [TILE_TYPE.VOID, TILE_TYPE.VOID, TILE_TYPE.VOID, TILE_TYPE.VOID, TILE_TYPE.VOID, TILE_TYPE.VOID], // TILE_TYPE.WALL: 0, TILE_TYPE.FLOOR: 1, TILE_TYPE.BPX: 2, GOAL: 3, TILE_TYPE.VOID: 4
    [TILE_TYPE.VOID, TILE_TYPE.VOID, TILE_TYPE.FLOOR, TILE_TYPE.FLOOR, TILE_TYPE.VOID, TILE_TYPE.VOID], 
    [TILE_TYPE.VOID, TILE_TYPE.WALL, TILE_TYPE.FLOOR, TILE_TYPE.FLOOR, TILE_TYPE.FLOOR, TILE_TYPE.VOID],
    [TILE_TYPE.VOID, TILE_TYPE.FLOOR, TILE_TYPE.FLOOR, TILE_TYPE.FLOOR, TILE_TYPE.BOX, TILE_TYPE.VOID],
    [TILE_TYPE.VOID, TILE_TYPE.FLOOR, TILE_TYPE.GOAL, TILE_TYPE.GOAL, TILE_TYPE.WALL, TILE_TYPE.VOID],
    [TILE_TYPE.VOID, TILE_TYPE.VOID, TILE_TYPE.VOID, TILE_TYPE.VOID, TILE_TYPE.VOID, TILE_TYPE.VOID]
  ]
};

let level2 = {
  label: "Level 2",
  optimalMoves: 5,
  playerStartingPosition: [[1, 1], [1, 4]],
  map: [
    [4, 4, 4, 4, 4],
    [4, 1, 4, 4, 4],
    [4, 1, 1, 1, 4],
    [4, 1, 1, 1, 4],
    [4, 1, 1, 3, 4],
    [4, 0, 1, 3, 4],
    [4, 4, 4, 4, 4]
]
};